<?php include 'header.phtml'?>
<?php if(isset($_SESSION['id_usuario'])) : ?>
<h2 class="p-1">Agregar Equipo</h2>
<form action="agregar equipo" method="POST" class="my-4">
    <div class="row">
        <div class="col-9">
            <div class="form-group">
                <label>Nombre</label>
                <input required name="nombre" type="text" class="form-control">
            </div>
        </div>

        <div class="col-9">
            <div class="form-group">
                <label>Pais</label>
                <input required name="pais" type="text" class="form-control">
            </div>
        </div>

        <div class="col-9">
            <div class="form-group">
                <label>Fundacion</label>
                <input required name="fundacion" type="date" class="form-control">
            </div>
        </div>

        <div class="col-9">
            <div class="form-group">
                <label>Estadio</label>
                <input required name="estadio" type="text" class="form-control">
            </div>
        </div>

        <div class="col-9">
            <div class="form-group">
                <label>Entrenador</label>
                <input required name="entrenador" type="text" class="form-control">
            </div>
        </div>
    </div>
    <button type="submit" class="btn btn-primary mt-2">Agregar</button>
</form>
<?php endif ?>