<?php require_once 'templates/header.phtml'?>

<h2 class="p-1">Editar Jugador</h2>
<!-- formulario de alta de tarea -->
<link rel="stylesheet" href="style.css">
<form action="editar jugador" method="POST" class="my-4" <?= $jugador->id_jugador ?>>
    <div class="row">
        <div class="col-9">
            <div class="form-group">
                <label>Nombre</label>
                <input required name="nombre" type="text" class="form-control" <?= $jugador->nombre ?>>
            </div>
        </div>

        <div class="col-3">
            <div class="form-group">
                <select required name="equipo" class="form-control">
                <label for="id_equipo">Equipo:</label>
            <option value="1">Argentinos Juniors</option>
            <option value="2">Arsenal</option>
            <option value="3">Atletico Tucuman</option>
            <option value="4">Banfield</option>
            <option value="5">Barracas Central</option>
            <option value="6">Belgrano</option>
            <option value="7">Boca Juniors</option>
            <option value="8">Central Cordoba</option>
            <option value="9">Colon</option>
            <option value="10">Defensa y Justicia</option>
            <option value="11">Estudiantes de La Plata</option>
            <option value="12">Gimnasia La Plata</option>
            <option value="13">Godoy Cruz</option>
            <option value="14">Huracan</option>
            <option value="15">Independiente</option>
            <option value="16">Instituto</option>
            <option value="17">Lanus</option>
            <option value="18">Newells Old Boys</option>
            <option value="19">Platense</option>
            <option value="20">Racing Club</option>
            <option value="21">River Plate</option>
            <option value="22">Rosario Central</option>
            <option value="23">San Lorenzo</option>
            <option value="24">Sarmiento</option>
            <option value="25">Talleres</option>
            <option value="26">Tigre</option>
            <option value="27">Unión</option>
            <option value="28">Velez Sarsfield</option>
            <?php foreach ($equipos as $equipo) {?>
        <option value="<?= $equipo->id_equipo ?>"><?= $equipo->nombre ?></option>
      <?php } ?>
                </select>
            </div>
        </div>

        <div class="col-9">
            <div class="form-group">
                <label>Fecha de nacimiento</label>
                <input required name="fecha_de_nacimiento" type="date" class="form-control" <?= $jugador->fecha_de_nacimiento ?>>
            </div>
        </div>

        <div class="col-9">
            <div class="form-group">
                <label>Nacionalidad</label>
                <input required name="nacionalidad" type="text" class="form-control" <?= $jugador->nacionalidad ?>>
            </div>
        </div>

        <div class="col-9">
            <div class="form-group">
                <label>Posicion</label>
                <input required name="posicion" type="text" class="form-control" <?= $jugador->posicion ?>>
            </div>
        </div>
    </div>

    <button type="submit" class="btn btn-primary mt-2">Editar</button>
</form>
<a href="jugadoresList.phtml" class="btn btn-primary">Atras</a>  

<?php include 'templates/footer.phtml'?>