<?php require 'templates/header.phtml' ?>

<div class="text-center">
        <h1>Bienvenido a Tu Sitio de Fútbol</h1>
    <main>
        <section>
        <div class="d-grid gap-2 col-6 mx-auto">
            <h2>Aca podras agregar a tu jugador favorito</h2>
            <p>Aquí puedes encontrar las últimas noticias y actualizaciones relacionadas con el mundo del fútbol.</p>
            <button class="btn btn-primary" type="button" href= "jugadoresList.phtml">Ver Jugadores</button>
        </div>
        </section>
        
        <section>
        <div class="d-grid gap-2 col-6 mx-auto">
            <h2>Aca podras agregar el equipo del que eres fanatico</h2>
            <p>Descubre los equipos y jugadores destacados de la temporada y sus logros.</p>
            <button class="btn btn-primary" type="button" href= "equiposList.phtml">Ver Equipos</button>
        </div>
        </section>
    </main>

<?php require 'templates/footer.phtml' ?>