<?php require 'templates/header.phtml' ?>

<h2>Jugador</h2>
<div class="container mt-4">
    <div class="card">
        <div class="card-header">
            <h5 class="card-title"><?= $jugador->nombre ?></h5>
        </div>
        <ul class="list-group">
    <li class="list-group-item">Id: <?= $jugador->id_jugador ?></li>
    <li class="list-group-item">Fecha_de_nacimiento: <?= $jugador->fecha_de_nacimiento ?></li>
    <li class="list-group-item">Nacionalidad: <?= $jugador->nacionalidad ?></li>
    <li class="list-group-item">Posicion: <?= $jugador->posicion ?></li>
    <li class="list-group-item">Equipo: <?= $jugador->nombre_equipo ?></li>
    </ul>
    </div>
    <a href="jugadoresInfo" class="btn btn-primary">Atras</a>
</div>

<?php require 'templates/footer.phtml' ?>