<?php require_once 'templates/header.phtml';
require 'templates/form_jugador.phtml'; ?>

<div class="d-grid gap-2 col-6 mx-auto">
  <?php if (isset($_SESSION['USER_ID'])) : ?>
    <a href="<?php echo BASE_URL . 'form_jugador/'; ?>" class="btn btn-success btn-sm">Agregar Jugador</a>
    <?php endif ?>
</div>

<ul class="list-group">
<div class="col-md-7 order-md-2">
<?php foreach($jugadores as $jugador): ?>
    <h2 class="nombre-jugador"><?= $jugador->nombre ?></h2>
    <p class="nombre-equipo">Equipo:<?= $jugador->nombre_equipo ?></p>
    <a href="<?php echo BASE_URL . 'jugador/' . $jugador->id_jugador; ?>" class="btn btn-primary btn-sm">Ver Detalle</a>
    <?php if (isset($_SESSION['USER_ID'])) : ?>
              <a href="deleteJugador/<?= $jugador->id_jugador ?>" class='btn btn-danger ml-auto'>Borrar</a>
              <a href="formEditarJugador/<?= $jugador->id_jugador ?>" type="button" class='btn btn-success ml-auto'>Editar</a>
            <?php endif ?>
    </li>
<?php endforeach ?>
</ul>

<?php require_once 'templates/footer.phtml' ?>